
import { SiteAnalysis } from "../types";

export const exportToMarkdown = (data: SiteAnalysis) => {
  const markdown = `
# SiteScout AI - Website Analysis Report
**Target URL:** ${data.url}
**Report Generated:** ${new Date().toLocaleString()}

---

## Executive Summary
${data.summary}

### Core Purpose
${data.purpose}

### Operational Flow
${data.howItWorks}

---

## Strategic Requirements

### Functional Requirements
${data.requirements.functional.map(item => `- ${item}`).join('\n')}

### Technical Requirements
${data.requirements.technical.map(item => `- ${item}`).join('\n')}

### UX / Design Requirements
${data.requirements.userExperience.map(item => `- ${item}`).join('\n')}

---

## Information Architecture & Site Mapping
${data.structure.map(item => `### ${item.page}\n${item.description}`).join('\n\n')}

---
*This report was generated by SiteScout AI Intelligence mapping.*
  `.trim();

  downloadFile(markdown, `SiteScout_Report_${data.url.replace(/[^a-z0-9]/gi, '_')}.md`, 'text/markdown');
};

export const exportToJSON = (data: SiteAnalysis) => {
  const json = JSON.stringify(data, null, 2);
  downloadFile(json, `SiteScout_Report_${data.url.replace(/[^a-z0-9]/gi, '_')}.json`, 'application/json');
};

const downloadFile = (content: string, fileName: string, contentType: string) => {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(file);
  a.href = url;
  a.download = fileName;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 100);
};
